### ISSUE TITLE
Naming for DRP and DAP properties in Spaxel

### ISSUE THREAD

**Issue by albireox** [marvin-manga/marvin_public_old#2]
Just opening a thread here to discuss how we want to rename (in case we want) `Spaxel.drp` and `Spaxel.dap`.

Kevin has suggested `Spaxel.spectrum` or `Spaxel.data` for DRP spectrum, and `Spaxel.measurements` for DAP properties.

Discuss!

**Comment by karenlmasters** [comment]
Perhaps spaxel.maps for DAP? I like spaxel.spectrum, although it's a bit long...

**Comment by bretthandrews** [comment]
I vote for `Spaxel.spectrum` because it is transparent. Maybe `Spaxel.properties` for DAP?

**Comment by albireox** [comment]
I like spectrum and properties (now that it think about it that might have been what Kevin suggested).

**Comment by havok2063** [comment]
I also like spectrum and properties.  I think Kevin suggested measurements as opposed to properties.  But properties is a tad more succint.
